### ISSUE TITLE
integrate util, regex and iguana

### ISSUE THREAD

**Issue by jurgenvinju** [iguana-parser/iguana#13]
For deployment and continuous integration and dependency simplicity, {c,sh,w}ould we merge these three projects?

* util
* regex
* iguana

into one single `iguana` project? in github, and a single POM file? 

Arguments in favor:

* The current administrative overhead for using and maintaining iguana is big, considering manual compilation and install, continous integration, deployment, the cost is 3 times the cost of a single project;
* There are no other clients for util and regex as far as I understand;
* The three projects will evolve in a synchronized fashion, expectedly.
* Additional (semantic) version management between each of three modules can be error-prone, while maybe not offering a significant benefit.
* The modules share dependencies between themselves as well.

Arguments against:

* This can be independent modules in principle, which might be reusable outside of iguana in principle
* The projects can be tested and evolved independently, in principle.

**Comment by afroozeh** [comment]
Yeah, I agree with your points to merge them back into a single project. The idea was to reuse them in Meerkat, but at the moment there is no plan for Meerkat, so it's a good idea to merge them back. Let's do that after fixing all unit tests.

**Comment by afroozeh** [comment]
This took a while :-) but I finally managed to fix all the tests and merged the projects into a single one.
