### ISSUE TITLE
Can't run iguana benchmark.

### ISSUE THREAD

**Issue by AnastasiyaRagozina** [iguana-parser/iguana#2]
Hello, I cloned repository with iguana project and decide to run benchmark to try it.

I found class csharp benchmark, create dubug configuration, change sourceDir to specify my tests. Exception occurs: java.lang.ClassNotFoundException: org.jgll.grammar.Grammar

Stack trace:

```
BenchmarkCSharp [Java Application]	
	org.iguana.benchmark.BenchmarkCSharp at localhost:11316	
		Thread [main] (Suspended (exception RuntimeException))	
			Grammar.load(File) line: 282		

``` 
I use JDK 8u45, eclipse Version: Luna Service Release 2 (4.4.2)
Build id: 20150219-0600.

Could you help me, please, to run your tests?

**Comment by afroozeh** [comment]
Hi, 

We have recently merged a lot of new experimental functionalities
into Iguana, so it's pretty messy at the moment. Sorry for that.
We plan to come back to Iguana next week and start making it stable again.

Are you trying to reproduce tests from our recent paper: 
"Faster, practical GLL parsing"
http://link.springer.com/chapter/10.1007%2F978-3-662-46663-6_5#page-1
(There is no pre-print available yet, but I will put it online if you don't
have it already)

I suspect we will have a working version, merged with new functionalities
at the end of July, but you don't have to wait until then. Please 
email me (afroozeh@gmail.com) and let me know what you are exactly
trying to do and then I will help you run the tests. Most probably you
need to revert to a version that we used before merge and then run the
tests.

**Comment by afroozeh** [comment]
@AnastasiyaRagozina We are gradually writing documentations how to use iguana here: http://iguana-parser.github.io, so I will close this issue.
