### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by ccarter-cs** [iguana-parser/iguana#3]
Couple of questions.

What is the proper way to build this project?
Can you start publishing builds to bintray or maven etc?

**Comment by afroozeh** [comment]
We are currently re-organizing Iguana into separate sub-projects. Iguana itself is a maven project, but parse-trees is written in Scala and we use SBT. For the moment, if you want to build Iguana, you need to get the needed subprojects, i.e., utils and parse-trees, and first build them and publish locally and then build Iguana. 

We are hit by a couple of deadlines and need to work on papers, but we plan to publish them as binary by end of this year, hopefully.

In the meantime if you have any questions or problems, please don't hesitate to contact us.

**Comment by hannahlindsley** [comment]
Hi,
I was wondering if you could give me a little guidance in traversing SPPFs.
Generally, I'm interested in generating a tree or set of trees from the
bottom up, and in filtering (pruning) an forest after it's built.

Do y'all happen to have documentation on traversal yet? I understand it's
early days, and I appreciate your time :D
I've looked through the visitation interface, but wasn't able to clearly
identify something I could use right off the bat.


Thank you!
Hannah

**Comment by afroozeh** [comment]
Hi Hannah,

We have facilities to traverse SPPF, but as you already noticed not yet well documented.
In one or two days we will come back to you with instructions how to traverse SPPF and Terms.

Thanks, 

Ali

**Comment by hannahlindsley** [comment]
Hey! Has anybody gotten a chance to look into this?

Thanks,
H

**Comment by afroozeh** [comment]
Hey! really sorry for not replying in this period. This publication process takes all our energy and there is not much time for coding. Anyway, I tried to set an example for you how you can use the resulting SPPF.
GLL produces binarized SPPFs to keep the cubic bound for worst case grammars. Binarized SPPFs are hard to work with, therefore, we provide default conversions to terms (an algebraic data type) that reflects the underlying grammar. This makes it much easier to navigate the terms.

We rewrote the SPPF part of Iguana in Scala, as it makes the whole coding experience very pleasant, especially when it comes to traversal. I put together an example of disambiguation by rewriting for you here: [Test1.scala](https://github.com/iguana-parser/iguana/blob/master/test/org/iguana/traversal/Test1.scala)

In this example, we have the ambiguous grammar `E ::= E + E | E * E | a` and we parse the input `a+a*a` with it. The default ambiguous terms are shown here: [original.pdf](https://github.com/iguana-parser/iguana/files/89847/original.pdf) and using the disambiguate function, as you wanted, we traverse the code bottom up, and remove the undesired parse tree, which gives us this: [disambiguated.pdf](https://github.com/iguana-parser/iguana/files/89850/disambiguated.pdf)

For traversal we used the [kiama](https://bitbucket.org/inkytonik/kiama) project. I think you should be able to find your way if you know Scala, but please don't hesitate to ask any questions you have. I'll try to be more responsive.

Btw, we are putting a website with documentation online [here](http://iguana-parser.github.io). The part about terms are missing, but we will try to put them as soon as possible.
